### ISSUE TITLE
Does not actually implement an OSRAM Lightify to homebridge interface yet

### ISSUE THREAD

**Issue by apexad** [hyun007/homebridge-lightify#1]
This plugin does not actually implement an interface to the OSRAM Lightify system to homebridge. Are you still working on it at all?

**Comment by fildy** [comment]
same issues with me

**Comment by g1lby** [comment]
would love to see any progress on this, too. I mean, not even a documentation.. Or are we asking too much by requesting that?

**Comment by apexad** [comment]
There are now several working lightify homebridge plugins. I am closing this issue.
